config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#new_guest'
  end
  devise_for :teachers
  devise_scope :teacher do
    post 'teachers/guest_sign_in', to: 'teachers/sessions#new_guest'
  end
  
  root to: "classrooms#index"
  resources :classrooms do
    resources :chatrooms, only: [:new, :create, :show] do
      resources :chats, only: [:create]
    end
    resources :take_overs, except: :index
    resources :homeworks, except: :index do
      resources :submissions, except: :index
    end
  end
  resources :informations do
    resources :inquiries, only: [:new, :create]
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :chatroom
  # バリデーション
  validates :text, :judgement, presence: true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  # TeachersテーブルとStudentsテーブルとClassroomsテーブルとのアソシエーション
  belongs_to :teacher
  belongs_to :student
  belongs_to :classroom
  has_many :chats
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  # 中間テーブルとのアソシエーション(throughより上に書かないといけない)
  has_many :classroom_teachers, dependent: :destroy
  has_many :classroom_students, dependent: :destroy
  # アソシエーション
  has_many :teachers, through: :classroom_teachers
  has_many :students, through: :classroom_students
  has_many :chatrooms
  has_many :take_overs
  has_many :homeworks
  # 同時に中間テーブルのレコードも更新
  accepts_nested_attributes_for :classroom_teachers, allow_destroy: true
  accepts_nested_attributes_for :classroom_students, allow_destroy: true
  
  # バリデーション
  validates :name, :year_month, :teacher_id, presence: true
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :student
  belongs_to :classroom
  # クラスルーム作成時のバリデーション
  validates :student_id, presence: true
end

app/models/classroom_teacher.rb
class ClassroomTeacher < ApplicationRecord
  belongs_to :teacher
  belongs_to :classroom
  # クラスルーム作成時のバリデーション
  validates :teacher_id, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'お知らせ' },
    { id: 3, name: '授業' },
    { id: 4, name: '進学' },
    { id: 5, name: '就職' },
    { id: 6, name: '行事' },
    { id: 7, name: '奨学金' },
    { id: 8, name: 'その他' },
  ]
 end

app/models/homework.rb
class Homework < ApplicationRecord
  # アソシエーション
  belongs_to :classroom
  belongs_to :teacher
  has_many :submissions
  # ActiveStorage
  has_one_attached :file

  # バリデーション
  validates :content, :start_time, :judgement, :classroom_id, :teacher_id, presence: true
end

app/models/information.rb
class Information < ApplicationRecord
  # アソシエーション
  belongs_to :teacher
  has_many :inquiries
  # ActiveHashのメソッド
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  # バリデーション
  with_options presence: true do
    validates :title
    validates :genre_id, numericality: { other_than: 1 }
    validates :content
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  # アソシエーション
  belongs_to :information
  belongs_to :teacher, optional: true
  belongs_to :student, optional: true

  validates :content, presence: true
end

app/models/status.rb
class Status < ActiveHash::Base
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: '事務局・運営' },
      { id: 3, name: '正社員講師・常勤講師' },
      { id: 4, name: '非常勤講師' },
    ]

  include ActiveHash::Associations
  has_many :teachers
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # アソシエーション
  has_many :classroom_students
  has_many :classrooms, through: :classroom_students
  has_many :submissions
  # carrierwaveの記述
  mount_uploader :image, ImageUploader
  # バリデーション
  with_options presence: true do
    validates :student_number
    validates :name, format: {with: /\A[A-Za-z 　一-龥]+\z/, message: 'はアルファベットか漢字で入力してください'}
    validates :name_k, format: {with: /\A[ァ-ヶー－ 　]+\z/, message: 'は全角カタカナのみで入力してください'}
    validates :nickname
    validates :image
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])\w{6,}\z/i, message: 'は半角英数字6文字以上で入力してください'}
    validates :birthday
  end

  # 期間の重複がないかどうか
  # classroom_studentsを作成する際に、classroom_studentsの中にあるその学生のidと紐づいているクラスが同じ期間のものだったらエラー文吐き出し
  # if 

  # ゲストログイン
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |student|
      student.student_number = Faker::Number.number(digits: 7)
      student.name = Faker::Name.name
      student.name_k = Gimei.name.katakana
      student.nickname = Gimei.name.last.katakana
      student.image = open('./db/fixtures/student.png')
      student.password = SecureRandom.urlsafe_base64
      student.birthday = Faker::Date.between(from: '1990-01-01', to: '2002-4-01')
    end
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  # アソシエーション
  belongs_to :homework
  belongs_to :student
  # ActiveStorage
  has_one_attached :file

  # バリデーション
  validates :content, :homework_id, :student_id, presence: true
end

app/models/take_over.rb
class TakeOver < ApplicationRecord
  # アソシエーション
  belongs_to :classroom
  belongs_to :teacher
  # バリデーション
  validates :start_time, :content, :detail, :appearance, :judgement, :classroom_id, :teacher_id, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # アソシエーション
  has_many :classroom_teachers
  has_many :classrooms, through: :classroom_teachers
  has_many :informations
  has_many :take_overs
  has_many :homeworks
  # ActiveHashのメソッド
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :status
  # carrierwaveの記述
  mount_uploader :image, ImageUploader
  # バリデーション
  with_options presence: true do
    validates :employee_number
    validates :status_id, numericality: { other_than: 1 }
    # with_options format: {with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/} do
    with_options format: {with: /\A[ぁ-んァ-ン一-龥]+\z/, message: 'は全角文字を使用してください'} do
      validates :last_name
      validates :first_name
    end
    with_options format: {with: /\A[ァ-ヶー－]+\z/, message: 'は全角カタカナのみで入力してください'} do
      validates :last_name_k
      validates :first_name_k
    end
    validates :image
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])\w{6,}\z/i, message: 'は半角英数字6文字以上で入力してください'}
    validates :nickname
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |teacher|
      # teacher.password = SecureRandom.urlsafe_base64
      gimei = Gimei.name
      teacher.employee_number = Faker::Number.number(digits: 6)
      teacher.status_id = Faker::Number.between(from: 2, to: 4)
      teacher.last_name = gimei.last.kanji
      teacher.first_name = gimei.first.kanji
      teacher.last_name_k = gimei.last.katakana
      teacher.first_name_k = gimei.first.katakana
      teacher.image = open('./db/fixtures/teacher.png')
      teacher.password = '1a1a1a1a'
      teacher.nickname = gimei.last.hiragana
    end
  end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/take_overs_helper.rb
module TakeOversHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassMatome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag 'favicon.png'%>
    <%# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/PP/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%# Bootstrap(JS)の呼び出し %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%# スマホでのviewport設定 %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_default_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="sideNav">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "講師はこちら", new_teacher_session_path, class: "nav-link"%></li>
      <li class="nav-item"><%= link_to "学生はこちら", new_student_session_path, class: "nav-link"%></li>
      <li class="nav-item"><%= link_to '講師ゲストログイン', teachers_guest_sign_in_path, method: :post, class: "nav-link"%></li>
      <li class="nav-item"><%= link_to '学生ゲストログイン', students_guest_sign_in_path, method: :post, class: "nav-link"%></li>
    </ul>
  </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_student_bar.html.erb
<%# 使用するページ…Classrooms#index,Informations#index,show %>
<%#= link_to student_path(current_student.id) do %>
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="sideNav">
  <a class="navbar-brand js-scroll-trigger" href="#">
    <span class="d-none d-lg-block"><%= image_tag current_student.image.url, class: "img-fluid img-profile rounded-circle mx-auto mb-2" %></span>
  </a>
    <div class="d-block"><%= current_student.nickname %></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to 'ログアウト', destroy_teacher_session_path, method: :delete, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "インフォメーション一覧", informations_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>

app/views/shared/_student_classroom_bar.html.erb
<%# 使用するページ…Classrooms#show,Homeworks#show,Submissions#new,show,edit,Chatrooms#show %>
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="sideNav">
  <a class="navbar-brand js-scroll-trigger" href="#">
      <span class="d-none d-lg-block"><%= image_tag current_student.image.url, class: "img-fluid img-profile rounded-circle mx-auto mb-2" %></span>
  </a>
  <div class="d-block"><%= current_student.nickname %></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "インフォメーション一覧", informations_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "トップページ", root_path, class: "nav-link" %></li>
      <li class="nav-item">
        <%= link_to classroom_chatrooms_path(@classroom.id), method: :post, class: "nav-link" do %>
          <%= "先生とチャットをする" %>
          <%# もしチャットルームがあったら通知を表示 %>
          <% @chatroom = Chatroom.find_by(classroom_id: @classroom.id, student_id: current_student.id) %>
          <% if @chatroom.present? %>
            <%# 未読の数をカウント %>
            <% @count = Chat.where(judgement: 1, chatroom_id: @chatroom.id,  checked: false).count %>
            <% if @count != 0 %>
              <div class="notification">
                <%= @count %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_teacher_bar.html.erb
<%# 使用するページ…Classrooms#index,Informations#index,new,show,edit %>
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="sideNav">
  <a class="navbar-brand js-scroll-trigger" href="#">
    <span class="d-none d-lg-block"><%= image_tag current_teacher.image.url, class: "img-fluid img-profile rounded-circle mx-auto mb-2" %></span>
  </a>
    <div class="d-block"><%= current_teacher.nickname %></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to 'ログアウト', destroy_teacher_session_path, method: :delete, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "クラス作成", new_classroom_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "インフォメーション作成", new_information_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "インフォメーション一覧", informations_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>

app/views/shared/_teacher_classroom_bar.html.erb
<%# 使用するページ…Classrooms#show,edit,Take_overs#new,show,edit,Homeworks#new,show,edit,Submissions#show %>

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="sideNav">
  <a class="navbar-brand js-scroll-trigger" href="#">
      <span class="d-none d-lg-block"><%= image_tag current_teacher.image.url, class: "img-fluid img-profile rounded-circle mx-auto mb-2" %></span>
  </a>
  <div class="d-block"><%= current_teacher.nickname %></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to "トップページ", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "授業記録作成", new_classroom_take_over_path(@classroom.id), class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "宿題作成", new_classroom_homework_path(@classroom.id), class: "nav-link" %></li>
      <%# 担任にのみ表示 %>
      <% if @classroom.teacher_id == current_teacher.id %>
        <li class="nav-item"><%= "学生チャット一覧" %></li>
        <%# <div class="box">
          <label for="inbox1">学生チャット一覧<div class="box_label"><%= image_tag "arrow_down.png", size: '15x15' % ></div></label>
          <input type="checkbox" id="inbox1" class="on-off">
        <div>%>
        <% @classroom.students.each do |student| %>
          <li class="nav-item">
            <%= link_to classroom_chatrooms_path(@classroom.id, student: student), method: :post, class: "nav-link" do %>
              <%= student.nickname %>
              <%# もしチャットルームがあったら通知を表示 %>
              <% @chatroom = Chatroom.find_by(classroom_id: @classroom.id, student_id: student.id) %>
              <% if @chatroom.present? %>
                <%# 未読の数をカウント %>
                <% @count = Chat.where(judgement: 2, chatroom_id: @chatroom.id,  checked: false).count %>
                <% if @count != 0 %>
                  <div class="notification">
                    <%= @count %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>