config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#new_guest'
  end
  devise_for :teachers
  devise_scope :teacher do
    post 'teachers/guest_sign_in', to: 'teachers/sessions#new_guest'
  end
  
  root to: "classrooms#index"
  resources :classrooms do
    resources :chatrooms, only: [:new, :create, :show] do
      resources :chats, only: [:create]
    end
    resources :take_overs, except: :index
    resources :homeworks, except: :index do
      resources :submissions, except: :index
    end
  end
  resources :informations do
    resources :inquiries, only: [:new, :create]
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  # アソシエーション
  belongs_to :homework
  belongs_to :student
  # ActiveStorage
  has_one_attached :file

  # バリデーション
  validates :content, :homework_id, :student_id, presence: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :authenticate_student!, only: [:new, :edit]
  before_action :set_classroom, except: :index
  before_action :set_homework, only: [:create, :show, :update]
  before_action :set_submission, only: [:show, :edit, :update]

  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)
    if @submission.valid?
      @submission.save
      redirect_to classroom_homework_path(@classroom.id, @homework.id)
    else
      render "submissions/new"
    end
  end

  def show
    @student = Student.find(@submission.student_id)
  end

  def edit
    if current_student.id != @submission.student_id 
      redirect_to classroom_path(@classroom.id)
    end
  end

  def update
    if @submission.update(submission_params)
      redirect_to classroom_path(@classroom.id)
    else
      render "submissions/edit"
    end
  end

  def destroy
    submission = Submission.find(params[:id])
    if submission.destroy
      redirect_to classroom_path(@classroom.id)
    else
      render "submissions/show"
    end
  end

  private

  def submission_params
    params.require(:submission).permit(:content, :file).merge(homework_id: @homework.id, student_id: current_student.id)
  end
  
  def set_classroom
    @classroom = Classroom.find(params[:classroom_id])
  end

  def set_homework
    @homework = Homework.find(params[:homework_id])
  end

  def set_submission
    @submission = Submission.find(params[:id])
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/edit.html.erb
<%= render "shared/student_classroom_bar" %>
<div class="input-flame">
  <h2>宿題</h2>
  <%= form_with url: classroom_homework_submission_path, model: @submission, local: true do |f| %>
    <%# エラー文 %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <%= f.label :content, "宿題", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_area :content, class: "form-control", placeholder: '宿題内容を入力してください' %>
    </div>
    <div class="form-group">
      <p><b>クリックしてファイルをアップロード</b></p>
      <%= f.file_field :file, name: 'item[images]', id: 'item-image' %>
      <div id="image-list" class="upload-image">
      <%# ここに<input id="item_image_[番号]" name="item[images][]" type="file">が入る%>
      </div>
    </div>

    <div class="submit">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/submissions/new.html.erb
<%= render "shared/student_classroom_bar" %>
<div class="input-flame">
  <h2>宿題</h2>
  <%= form_with url: classroom_homework_submissions_path, model: @submission, local: true do |f| %>
    <%# エラー文 %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <%= f.label :content, "宿題", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_area :content, class: "form-control", placeholder: '宿題内容を入力してください' %>
    </div>
    <div class="form-group">
      <p><b>クリックしてファイルをアップロード</b></p>
      <%= f.file_field :file, name: 'item[images]', id: 'item-image' %>
      <div id="image-list" class="upload-image">
      <%# ここに<input id="item_image_[番号]" name="item[images][]" type="file">が入る%>
      </div>
    </div>

    <div class="submit">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/submissions/show.html.erb
<%# サイドバー %>
<% if teacher_signed_in? %>
  <%= render "shared/teacher_classroom_bar" %>
<% else %>
  <%= render "shared/student_classroom_bar" %>
<% end %>

<h1>Submissions#show</h1>
<div class="btn-box">
  <% if teacher_signed_in? || current_student.id == @submission.student_id %>
    <div class="col-sm-8">
      <div class="form-group">
        名前：
        <%= @student.nickname %>
      </div>
      <div class="form-group">
        提出時間：
        <%= l(@submission.created_at, format: :default, class: "form-label") %>
      </div>
      <div class="form-group">
        内容：
        <%= @submission.content %>
      </div>
      <%# もしファイルがあればファイルを表示 %>
      <% if @submission.file.attached? %>
        <strong>ダウンロード:</strong>
        <%= link_to "添付ファイル" ,rails_blob_path(@submission.file) %>
      <% end %>
    <% end %>
  </div>
  <% if student_signed_in? && current_student.id == @submission.student_id %>
    <div class="col-md-2">
      <%= link_to '編集する', edit_classroom_homework_submission_path(@classroom.id, @homework.id, @submission.id), method: :get, class: "btn-primary" %>
      <%= link_to '削除する', classroom_homework_submission_path(@classroom.id, @homework.id, @submission.id), method: :delete, data: { confirm: '削除しますか？' }, class: "btn-primary" %>
    </div>
  <% end %>
</div>