config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#new_guest'
  end
  devise_for :teachers
  devise_scope :teacher do
    post 'teachers/guest_sign_in', to: 'teachers/sessions#new_guest'
  end
  
  root to: "classrooms#index"
  resources :classrooms do
    resources :chatrooms, only: [:new, :create, :show] do
      resources :chats, only: [:create]
    end
    resources :take_overs, except: :index
    resources :homeworks, except: :index do
      resources :submissions, except: :index
    end
  end
  resources :informations do
    resources :inquiries, only: [:new, :create]
  end
end

app/models/information.rb
class Information < ApplicationRecord
  # アソシエーション
  belongs_to :teacher
  has_many :inquiries
  # ActiveHashのメソッド
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  # バリデーション
  with_options presence: true do
    validates :title
    validates :genre_id, numericality: { other_than: 1 }
    validates :content
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  # 学生は一部参照不可
  before_action :authenticate_teacher!, except: [:index, :show]
  before_action :set_information, only: [:show, :edit, :update]


  def index
    @informations = Information.all.order('created_at DESC')
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    if @information.valid?
      @information.save
      redirect_to root_path
    else
      render :new 
    end
  end

  def show
    @inquiry = Inquiry.new
    @inquiries = Inquiry.where(information_id: params[:id])
    @inquiries.each do |inquiry|
      if inquiry.teacher_id.present?
        @teacher = Teacher.find(inquiry.teacher_id)
      elsif inquiry.student_id.present?
        @student = Student.find(inquiry.student_id)
      end
    end
  end

  def edit
    if current_teacher.id != @information.teacher_id 
      redirect_to root_path
    end
  end

  def update
    if @information.update(information_params)
      redirect_to root_path
    else
      render "informations/edit"
    end
  end

  def destroy
    information = Information.find(params[:id])
    if information.destroy
      redirect_to root_path
    else
      render "informations/show"
    end
  end

  private

  def information_params
    params.require(:information).permit(:title, :genre_id, :content).merge(teacher_id: current_teacher.id)
  end

  def set_information
    @information = Information.find(params[:id])
  end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/edit.html.erb
<%= render "shared/teacher_bar" %>
<div class="input-flame">
  <%= form_with url: information_path, model: @information, method: :patch, local: true do |f| %>
    <%# エラー文 %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <%= f.label :title, "タイトル", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_field :title, class: "form-control", placeholder: 'タイトルを入力してください' %>
    </div>

    <div class="form-group">
      <%= f.label :genre, "ジャンル", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre"}) %>
  </div>

    <div class="form-group">
      <%= f.label :contetnt, "内容", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_area :content, class: "form-control", placeholder: '内容を入力してください' %>
    </div>


    <div class="btn-contents">
      <%= f.submit class: "btn-primary"%>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    </div>
  <% end %>
</div>

app/views/informations/index.html.erb
<% if teacher_signed_in? %>
  <%= render "shared/teacher_bar" %>
<% elsif student_signed_in? %>
  <%= render "shared/student_bar" %>
<% end %>
<% @informations.each do |information| %>
  <div class='information'>
    <%= link_to information_path(information.id), class: "info-a" do %>
      <h4><%= information.title %></h4>
      <div class="genre-icon d-inline">
        <%= information.genre.name %>
      </div>
      <div class='info-content'>
        <%= information.content %>
      </div>
      <p><%= information.teacher.nickname %></p>
    <% end %>
  </div>
<% end %>

app/views/informations/new.html.erb
<%= render "shared/teacher_bar" %>
<div class="input-flame">
  <%= form_with url: informations_path, model: @information, method: :post, local: true do |f| %>
    <%# エラー文 %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <h3>共有する情報を入力してください</h3>
      <%= f.label :title, "タイトル", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_field :title, class: "form-control", placeholder: 'タイトルを入力してください' %>
    </div>

    <div class="form-group">
      <%= f.label :genre, "ジャンル", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre"}) %>
  </div>

    <div class="form-group">
      <%= f.label :contetnt, "内容", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_area :content, class: "form-control", placeholder: '内容を入力してください' %>
    </div>


    <div class="btn-contents">
      <%= f.submit class: "btn-primary"%>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    </div>
  <% end %>
</div>

app/views/informations/show.html.erb
<% if teacher_signed_in? %>
  <%= render "shared/teacher_bar" %>
<% elsif student_signed_in? %>
  <%= render "shared/student_bar" %>
<% end %>
<div class="btn-box">
  <div class="col-sm-8 margin">
    <div class="date-and-time">
      <%= l @information.created_at %>
    </div>
    <h2><%= @information.title %></h2>
      <p>ジャンル：<%= @information.genre.name %></p>
      <%# <div class='info-content'> %>
        <p>内容：<%= @information.content %></p>
      <%# </div> %>
      <p>先生：<%= @information.teacher.nickname %>先生</p>

    <%# 質問投稿フォーム %>
    <div class='inquiry'>
      <%= form_with url: information_inquiries_path(@information.id), model: @inquiry, method: :post, local: true do |f| %>
        <%# エラー文 %>
        <%= render 'shared/error_messages', model: f.object %>

        <div class=''>
          <%= f.label :質問, class: ''%>
          <div class=''>
            <%= f.text_area :content, class: '', placeholder: '質問を入力してください'%>
          </div>
        </div>

        <div class=''>
          <div class=''>
            <%= f.submit "質問する", class: 'btn-primary'%>
          </div>
        </div>
      <% end %>
    </div>
    <%# /質問投稿フォーム %>

    <%# 質問一覧表示 %>
    <% @inquiries.each do |inquiry| %>
      <div class="inquiry-box">
        <div class="inquiry-p">
          <% if inquiry.teacher_id.present? %>
            <p><%= @teacher.nickname %>先生</p>
          <% elsif inquiry.student_id.present? %>
            <p><%= @student.nickname %></p>
          <% end %>
          <%= l inquiry.created_at %>
        </div>
        <p><%= inquiry.content %></p>
      </div>
    <% end %>
    <%# /質問一覧表示 %>
  </div>

  <% if teacher_signed_in? && current_teacher.id == @information.teacher_id %>
    <div class="col-md-2">
      <%= link_to '編集する', edit_information_path(@information.id), method: :get, class: "btn-primary" %>
      <%= link_to '削除する', information_path(@information.id), method: :delete, data: { confirm: '削除しますか？' }, class: "btn-primary" %>
    </div>
  <% end %>
</div>