config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_scope :student do
    post 'students/guest_sign_in', to: 'students/sessions#new_guest'
  end
  devise_for :teachers
  devise_scope :teacher do
    post 'teachers/guest_sign_in', to: 'teachers/sessions#new_guest'
  end
  
  root to: "classrooms#index"
  resources :classrooms do
    resources :chatrooms, only: [:new, :create, :show] do
      resources :chats, only: [:create]
    end
    resources :take_overs, except: :index
    resources :homeworks, except: :index do
      resources :submissions, except: :index
    end
  end
  resources :informations do
    resources :inquiries, only: [:new, :create]
  end
end

app/models/homework.rb
class Homework < ApplicationRecord
  # アソシエーション
  belongs_to :classroom
  belongs_to :teacher
  has_many :submissions
  # ActiveStorage
  has_one_attached :file

  # バリデーション
  validates :content, :start_time, :judgement, :classroom_id, :teacher_id, presence: true
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  # 学生は一部参照不可
  before_action :authenticate_teacher!, except: [:show]
  before_action :set_classroom, except: :index
  before_action :set_homework, only: [:show, :edit, :update]
  
  def new
    @homework = Homework.new
  end

  def create
    @homework = Homework.new(homework_params)
    if @homework.valid?
      @homework.save
      redirect_to classroom_path(@classroom.id)
    else
      render "homeworks/new"
    end
  end

  def show
  end

  def edit
    if current_teacher.id != @homework.teacher_id 
      redirect_to classroom_path(@classroom.id)
    end
  end

  def update
    if @homework.update(homework_params)
      redirect_to classroom_path(@classroom.id)
    else
      render "homeworks/edit"
    end
  end

  def destroy
    homework = Homework.find(params[:id])
    if homework.destroy
      redirect_to classroom_path(@classroom.id)
    else
      render "homeworks/show"
    end
  end

  private

  def homework_params
    params.require(:homework).permit(:start_time, :content, :judgement, :file).merge(classroom_id: @classroom.id, teacher_id: current_teacher.id)
  end

  def set_classroom
    @classroom = Classroom.find(params[:classroom_id])
  end

  def set_homework
    @homework = Homework.find(params[:id])
  end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/edit.html.erb
<%= render "shared/teacher_classroom_bar" %>
<div class="input-flame">
  <h2>宿題編集</h2>
  <%= form_with url: classroom_homework_path, model: @homework, local: true do |f| %>
    <%# エラー文 %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <%= f.label :start_time, "宿題を出した日", class: "form-label" %>
      <span class="indispensable">必須</span>
      <div class="select-box">
        <%= f.date_select :start_time %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content, "宿題内容", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_area :content, class: "form-control", placeholder: '宿題内容を入力してください' %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :judgement, value: 3 %>
    </div>
    <div class="form-group">
      <p><b>クリックしてファイルをアップロード</b></p>
      <%= f.file_field :file %>
    </div>

    <div class="submit">
      <%= f.submit "変更する" %>
    </div>
  <% end %>
</div>

app/views/homeworks/new.html.erb
<%= render "shared/teacher_classroom_bar" %>
<div class="input-flame">
  <h2>宿題入力</h2>
  <%= form_with url: classroom_homeworks_path, model: @homework, local: true do |f| %>
    <%# エラー文 %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <%= f.label :start_time, "宿題を出した日", class: "form-label" %>
      <span class="indispensable">必須</span>
      <div class="select-box">
        <%= f.date_select :start_time %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :content, "宿題内容", class: "form-label" %>
      <span class="indispensable">必須</span>
      <%= f.text_area :content, class: "form-control", placeholder: '宿題内容を入力してください' %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :judgement, value: 3 %>
    </div>
    <div class="form-group">
      <p><b>クリックしてファイルをアップロード</b></p>
      <%= f.file_field :file %>
    </div>

    <div class="submit">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/homeworks/show.html.erb
<%# サイドバー %>
<% if teacher_signed_in? %>
  <%= render "shared/teacher_classroom_bar" %>
<% else %>
  <%= render "shared/student_classroom_bar" %>
<% end %>
<div class="btn-box">
  <div class="col-sm-8 ">
    <div class="form-group d-inline top">
      宿題内容
    </div>
    ：<%= @homework.content %>
  <% if @homework.file.attached? %>
    <strong>ダウンロード:</strong>
    <%= link_to "添付ファイル" ,rails_blob_path(@homework.file) %>
  <% end %>
  </div>
  <% if teacher_signed_in? && current_teacher.id == @homework.teacher_id %>
    <div class="col-md-2">
      <%= link_to '編集', edit_classroom_homework_path(@classroom.id, @homework.id), method: :get, class: "btn-primary" %>
      <%= link_to '削除', classroom_homework_path(@classroom.id, @homework.id), method: :delete, data: { confirm: '削除しますか？' }, class: "btn-primary" %>
    </div>
  <% end %>
</div>


<% if teacher_signed_in? %>
  <% @classroom.students.each do |student| %>
    <% submission = Submission.find_by(student_id: student.id, homework_id: @homework.id) %>
    <div class="submission-box">
      <%= student.nickname %>
      <% if submission.present? %>
        <span class="indispensable">提出</span>
        <%# 提出した日付・時間 %>
        <%= l submission.created_at %>
        <%# 宿題確認画面への遷移ボタン %>
        <div class="btn-contents">
          <%= link_to "宿題確認", classroom_homework_submission_path(@classroom.id, @homework.id, submission.id) %>
        </div>
        <% else %>
      <% end %>
    </div>
  <% end %>
<% elsif student_signed_in? %>
  <%= link_to "宿題提出", new_classroom_homework_submission_path(@classroom.id, @homework.id), class: "nav-link" %>

    <% submission = Submission.where(student_id: current_student.id, homework_id: @homework.id) %>
    <% if submission.exists? && current_student.id == submission.student_id %>
      <div class="submission-box">
        <span class="indispensable">提出</span>
        <%# 提出した日付・時間 %>
        <%= l submission.created_at %>
        <%# 宿題確認画面への遷移ボタン %>
        <div class="btn-contents">
          <%= link_to "宿題確認", classroom_homework_submission_path(@classroom.id, @homework.id, submission.id) %>
        </div>
      </div>
    <% end %>

<% end %>